export const CATEGORIES_GET_REQUEST = 'CATEGORY_GET_REQUEST';
export const CATEGORIES_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORIES_GET_FAIL = 'CATEGORY_GET_FAIL';

export const CATEGORY_GET_REQUEST = 'CATEGORY_GET_REQUEST';
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_FAIL = 'CATEGORY_GET_FAIL';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';
export const CATEGORY_DELETE_RESET = 'CATEGORY_DELETE_RESET';

export const CATEGORYSUB_GET_REQUEST = 'CATEGORYSUB_GET_REQUEST';
export const CATEGORYSUB_GET_SUCCESS = 'CATEGORYSUB_GET_SUCCESS';
export const CATEGORYSUB_GET_FAIL = 'CATEGORYSUB_GET_FAIL';
