export const SUBS_GET_REQUEST = 'SUB_GET_REQUEST';
export const SUBS_GET_SUCCESS = 'SUB_GET_SUCCESS';
export const SUBS_GET_FAIL = 'SUB_GET_FAIL';

export const SUB_GET_REQUEST = 'SUB_GET_REQUEST';
export const SUB_GET_SUCCESS = 'SUB_GET_SUCCESS';
export const SUB_GET_FAIL = 'SUB_GET_FAIL';

export const SUB_CREATE_REQUEST = 'SUB_CREATE_REQUEST';
export const SUB_CREATE_SUCCESS = 'SUB_CREATE_SUCCESS';
export const SUB_CREATE_FAIL = 'SUB_CREATE_FAIL';
export const SUB_CREATE_RESET = 'SUB_CREATE_RESET';

export const SUB_UPDATE_REQUEST = 'SUB_UPDATE_REQUEST';
export const SUB_UPDATE_SUCCESS = 'SUB_UPDATE_SUCCESS';
export const SUB_UPDATE_FAIL = 'SUB_UPDATE_FAIL';
export const SUB_UPDATE_RESET = 'SUB_UPDATE_RESET';

export const SUB_DELETE_REQUEST = 'SUB_DELETE_REQUEST';
export const SUB_DELETE_SUCCESS = 'SUB_DELETE_SUCCESS';
export const SUB_DELETE_FAIL = 'SUB_DELETE_FAIL';
export const SUB_DELETE_RESET = 'SUB_DELETE_RESET';
